title: My Test Site
description: Reading - Writing - Publishing - This & That
author: "© 2002 - 2024 My Test Site"
show_downloads: false

# Build settings
theme: minima
plugins:
  - jekyll-feed

#base_url: /gh-pages-minima-starter

# Minima social links
#github_username: 
#linkedin_username:
#rss: rss

# Minima: show excerpts in the frontpage
paginate: 5
show_excerpts: true

minima:
  date_format: "%d %B %Y"

# Minima: custom header links
header_pages:
  - _pages/about.md
  - _pages/blog.md
  - _pages/my-books.md
  - _pages/for-writers.md
  - _pages/for-readers.md
  - _pages/contact.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md